### ISSUE TITLE
2.x.x - Alpha release todo list

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/hummingbird#348]
- [x] Convert more of the samples
  - [x] https://github.com/hummingbird-project/hummingbird-examples/pull/51
- [x] Fix up HummingbirdLambda https://github.com/hummingbird-project/hummingbird-lambda/pull/13
- [x] Land OpenAPI PR https://github.com/swift-server/swift-openapi-hummingbird/pull/8
- [x] Lambda documentation
- [ ] Release notes
- [x] Update template for 2.x.x
- [x] Update documentation for HummingbirdFoundation merge
- [x] Edit package dependencies for alpha version once hummingbird is out
